comp:
	javac -classpath .\junit.jar Test_unitaire1.java

run:
	java -classpath .\junit.jar;. Test_unitaire1

run2:
	java -classpath .\junit.jar;. Test_unitaire1 coucou

run3:
	java -classpath .\junit.jar;. junit.awtui.TestRunner
