all:
	bcc32 -c alloc.c check.c cppspec.cpp list.c inifile.c config.c init.c internal.c log.c inifile.c user.c
	tlib mss32.lib +alloc.obj +check.obj +cppspec.obj +list.obj +inifile.obj +config.obj +init.obj +internal.obj +log.obj +inifile.obj +user.obj

